"""Publish docs/hiqa-2026/open-issues.md as the IG page input/pagecontent/open-issues.md.

The docs file is the source of truth; the page is generated so the two cannot drift.
Run: python scripts/hiqa/sync_open_issues.py [--check]
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'docs', 'hiqa-2026', 'open-issues.md')
DST = os.path.join(ROOT, 'input', 'pagecontent', 'open-issues.md')

HEADER = '''<!-- GENERATED by scripts/hiqa/sync_open_issues.py from docs/hiqa-2026/open-issues.md. Do not edit. -->

<div class="note-to-balloters" markdown="1">

**Requires Clarification.** These are the points where the HIQA draft ePrescription and eDispensation standard
(September 2026), or the other authoritative sources available to this proof of concept, do not settle what this IG
should do.
Nothing here is invented: where the IG needs a value in the meantime it uses a clearly named placeholder
and points back to this list. 
</div>

'''


def render():
    text = open(SRC, encoding='utf-8').read().replace('\r\n', '\n')
    text = re.sub(r'^# [^\n]*\n+', '', text, count=1)          # the page title comes from sushi-config
    text = re.sub(r'^(#{2,5}) ', lambda m: '#' * (len(m.group(1)) + 1) + ' ', text, flags=re.M)  # IG pages start at ###
    return HEADER + text.rstrip('\n') + '\n'


def main(check):
    new = render()
    old = open(DST, encoding='utf-8').read().replace('\r\n', '\n') if os.path.exists(DST) else ''
    if check:
        if new != old:
            print(f'{os.path.relpath(DST, ROOT)} is out of date: run python scripts/hiqa/sync_open_issues.py')
            return 1
        print('open-issues page is current')
        return 0
    open(DST, 'w', encoding='utf-8', newline='\n').write(new)
    print('wrote', os.path.relpath(DST, ROOT))
    return 0


if __name__ == '__main__':
    sys.exit(main('--check' in sys.argv))
