// Electronic Prescription Group (ePG) examples with several electronic prescriptions (eP) each (ADR-003).
// Generated by a script; SNOMED CT codings declare the Irish Edition ($SCTIE); codes: NMPC VMPs (SNOMED CT Irish Edition, verified in the NMPC Meds Catalogue) through the
// Medication examples, which also carry SNOMED CT and ATC; SNOMED CT indications, routes, instructions and units of
// presentation checked on tx.fhir.org; UCUM for strength-based and liquid doses. All people are fictional.

// ═══ ePG 11: cardiovascular and diabetes review, four medicines ═══

Instance: hiqa-rx-epg11-amlodipine
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 11 – eP 1: amlodipine 5 mg once a day"
Description: "Amlodipine 5 mg (NMPC VMP 267451000220105, ATC C08CA01) for essential hypertension: continuous, 28-day supply, 5 repeats."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000011-1"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000011"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-mpd-medication-amlodipine-5)
* subject = Reference(hiqa-patient-declan-walsh)
* supportingInformation = Reference(hiqa-allergies-declan-nilknown)
* authoredOn = "2026-10-01T09:30:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#59621000 "Essential hypertension"
* dosageInstruction[0].text = "Take one tablet once a day"
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732936001 "Tablet"
* dispenseRequest.quantity = 28 $SCT#732936001 "Tablet"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.numberOfRepeatsAllowed = 5
* dispenseRequest.validityPeriod.start = "2026-10-01"
* dispenseRequest.validityPeriod.end = "2027-03-31"
* substitution.allowedBoolean = true

Instance: hiqa-rx-epg11-ramipril
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 11 – eP 2: ramipril 5 mg once a day"
Description: "Ramipril 5 mg capsules (NMPC VMP 716371000220101) for essential hypertension."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000011-2"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000011"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-mpd-medication-ramipril-5)
* subject = Reference(hiqa-patient-declan-walsh)
* supportingInformation = Reference(hiqa-allergies-declan-nilknown)
* authoredOn = "2026-10-01T09:30:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#59621000 "Essential hypertension"
* dosageInstruction[0].text = "Take one capsule once a day"
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732937005 "Capsule"
* dispenseRequest.quantity = 28 $SCT#732937005 "Capsule"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.numberOfRepeatsAllowed = 5
* dispenseRequest.validityPeriod.start = "2026-10-01"
* dispenseRequest.validityPeriod.end = "2027-03-31"
* substitution.allowedBoolean = true

Instance: hiqa-rx-epg11-atorvastatin
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 11 – eP 3: atorvastatin 20 mg at night"
Description: "Atorvastatin 20 mg (NMPC VMP 254311000220102) for hypercholesterolaemia, taken at bedtime (timing.repeat.when HS)."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000011-3"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000011"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-mpd-medication-atorvastatin-20)
* subject = Reference(hiqa-patient-declan-walsh)
* supportingInformation = Reference(hiqa-allergies-declan-nilknown)
* authoredOn = "2026-10-01T09:30:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#13644009 "Hypercholesterolemia"
* dosageInstruction[0].text = "Take one tablet at night"
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #HS
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732936001 "Tablet"
* dispenseRequest.quantity = 28 $SCT#732936001 "Tablet"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.numberOfRepeatsAllowed = 5
* dispenseRequest.validityPeriod.start = "2026-10-01"
* dispenseRequest.validityPeriod.end = "2027-03-31"
* substitution.allowedBoolean = true

Instance: hiqa-rx-epg11-metformin
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 11 – eP 4: metformin 500 mg twice a day with food"
Description: "Metformin 500 mg (NMPC VMP 718271000220105) for type 2 diabetes, with the coded additional instruction 311504000 |With or after food|."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000011-4"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000011"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-mpd-medication-metformin-500)
* subject = Reference(hiqa-patient-declan-walsh)
* supportingInformation = Reference(hiqa-allergies-declan-nilknown)
* authoredOn = "2026-10-01T09:30:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#44054006 "Type 2 diabetes mellitus"
* dosageInstruction[0].text = "Take one tablet twice a day with or after food"
* dosageInstruction[=].additionalInstruction = $SCTIE#311504000 "With or after food"
* dosageInstruction[=].timing.repeat.frequency = 2
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732936001 "Tablet"
* dispenseRequest.quantity = 56 $SCT#732936001 "Tablet"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.numberOfRepeatsAllowed = 5
* dispenseRequest.validityPeriod.start = "2026-10-01"
* dispenseRequest.validityPeriod.end = "2027-03-31"
* substitution.allowedBoolean = true

Instance: hiqa-md-epg11-amlodipine
InstanceOf: IEMpdMedicationDispenseEDispensation
Usage: #example
Title: "ePG 11 – eDispensation of eP 1"
Description: "First supply of eP 1 (28 tablets)."
* identifier[0].system = "urn:ietf:rfc:3986"
* identifier[=].value = "urn:uuid:57f1db7f-bba2-55d9-81dd-2c3cf2c0c478"
* extension[recorded].valueDateTime = "2026-10-01T15:05:00+01:00"
* status = #completed
* medicationReference = Reference(ie-mpd-medication-amlodipine-5)
* subject = Reference(hiqa-patient-declan-walsh)
* performer[0].actor = Reference(hiqa-prac-pharmacist-farrell)
* performer[+].actor = Reference(hiqa-org-pharmacy)
* authorizingPrescription = Reference(hiqa-rx-epg11-amlodipine)
* type = http://terminology.hl7.org/CodeSystem/v3-ActCode#FF "First Fill"
* quantity = 28 $SCT#732936001 "Tablet"
* whenHandedOver = "2026-10-01T15:05:00+01:00"
* receiver = Reference(hiqa-patient-declan-walsh)
* dosageInstruction[0].text = "Take one tablet once a day"
* substitution.wasSubstituted = false

Instance: hiqa-md-epg11-metformin
InstanceOf: IEMpdMedicationDispenseEDispensation
Usage: #example
Title: "ePG 11 – eDispensation of eP 4"
Description: "First supply of eP 4 (56 tablets)."
* identifier[0].system = "urn:ietf:rfc:3986"
* identifier[=].value = "urn:uuid:bee01e93-1051-5dc4-b5e8-9c35d8a8cf37"
* extension[recorded].valueDateTime = "2026-10-01T15:05:00+01:00"
* status = #completed
* medicationReference = Reference(ie-mpd-medication-metformin-500)
* subject = Reference(hiqa-patient-declan-walsh)
* performer[0].actor = Reference(hiqa-prac-pharmacist-farrell)
* performer[+].actor = Reference(hiqa-org-pharmacy)
* authorizingPrescription = Reference(hiqa-rx-epg11-metformin)
* type = http://terminology.hl7.org/CodeSystem/v3-ActCode#FF "First Fill"
* quantity = 56 $SCT#732936001 "Tablet"
* whenHandedOver = "2026-10-01T15:05:00+01:00"
* receiver = Reference(hiqa-patient-declan-walsh)
* dosageInstruction[0].text = "Take one tablet twice a day with or after food"
* substitution.wasSubstituted = false

Instance: hiqa-grp-epg11-cardiometabolic
InstanceOf: IEMpdPrescriptionGroupHeader
Usage: #example
Title: "ePG 11 – Prescription group header: cardiovascular and diabetes review, four medicines"
Description: "Group-level data (HIQA EP 3.1 to 3.5) for ePG 11: 4 electronic prescriptions issued together."
* status = #active
* insert PrescriptionGroup(9-RX-2026-000011, hiqa-patient-declan-walsh, 2026-10-01T09:30:00+01:00, hiqa-rx-epg11-amlodipine)
* action[+].resource = Reference(hiqa-rx-epg11-ramipril)
* action[+].resource = Reference(hiqa-rx-epg11-atorvastatin)
* action[+].resource = Reference(hiqa-rx-epg11-metformin)

Instance: hiqa-bundle-epg11-cardiometabolic
InstanceOf: IEMpdElectronicPrescriptionGroup
Usage: #example
Title: "ePG 11 – Electronic Prescription Group: cardiovascular and diabetes review, four medicines"
Description: "Four continuous electronic prescriptions issued together at a GP review: amlodipine, ramipril, atorvastatin (at night) and metformin (with food), each with 5 repeats. Two of the four have been dispensed so far, so the group is active with a mix of dispensed and not-yet-dispensed eP. Product-based doses use SNOMED CT units of presentation."
* identifier.system = $NePS
* identifier.value = "9-RX-2026-000011"
* type = #collection
* timestamp = "2026-10-01T15:10:00+01:00"
* insert HIQAEntry(Patient, hiqa-patient-declan-walsh)
* insert HIQAEntry(RequestGroup, hiqa-grp-epg11-cardiometabolic)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg11-amlodipine)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg11-ramipril)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg11-atorvastatin)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg11-metformin)
* insert HIQAEntry(List, hiqa-allergies-declan-nilknown)
* insert HIQAEntry(PractitionerRole, hiqa-role-gp-nolan)
* insert HIQAEntry(Practitioner, hiqa-prac-gp-nolan)
* insert HIQAEntry(Organization, hiqa-org-gp-practice)
* insert HIQAEntry(Medication, ie-mpd-medication-amlodipine-5)
* insert HIQAEntry(Medication, ie-mpd-medication-ramipril-5)
* insert HIQAEntry(Medication, ie-mpd-medication-atorvastatin-20)
* insert HIQAEntry(Medication, ie-mpd-medication-metformin-500)
* insert HIQAEntry(MedicationDispense, hiqa-md-epg11-amlodipine)
* insert HIQAEntry(MedicationDispense, hiqa-md-epg11-metformin)
* insert HIQAEntry(Practitioner, hiqa-prac-pharmacist-farrell)
* insert HIQAEntry(Organization, hiqa-org-pharmacy)

// ═══ ePG 12: basal-bolus insulin, two medicines ═══

Instance: hiqa-rx-epg12-glargine
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 12 – eP 1: insulin glargine 20 units at bedtime"
Description: "Insulin glargine 100 units/mL pre-filled pen (NMPC VMP 529881000220106) for type 1 diabetes: 20 units subcutaneously at bedtime; supply of 5 pens (733006000 |Pen|)."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000012-1"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000012"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-medication-insulin-glargine)
* subject = Reference(hiqa-patient-tomas-quinn)
* supportingInformation = Reference(hiqa-allergies-tomas-nilknown)
* authoredOn = "2026-10-02T11:00:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#46635009 "Type 1 diabetes mellitus"
* dosageInstruction[0].text = "Inject 20 units under the skin at bedtime"
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #HS
* dosageInstruction[=].route = $SCTIE#34206005 "Subcutaneous route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 20 '[iU]' "units"
* dispenseRequest.quantity = 5 $SCT#733006000 "Pen"
* dispenseRequest.numberOfRepeatsAllowed = 3
* dispenseRequest.validityPeriod.start = "2026-10-02"
* dispenseRequest.validityPeriod.end = "2027-04-01"
* substitution.allowedBoolean = true

Instance: hiqa-rx-epg12-aspart
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 12 – eP 2: insulin aspart with meals"
Description: "Insulin aspart 100 units/mL cartridges (NMPC VMP 525351000220105): three concurrent dosages sharing sequence 1, before breakfast (ACM), lunch (ACD) and the evening meal (ACV); supply of 10 cartridges (732988008 |Cartridge|)."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000012-2"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000012"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-medication-insulin-aspart)
* subject = Reference(hiqa-patient-tomas-quinn)
* supportingInformation = Reference(hiqa-allergies-tomas-nilknown)
* authoredOn = "2026-10-02T11:00:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#46635009 "Type 1 diabetes mellitus"
* dosageInstruction[0].text = "Inject 6 units before breakfast"
* dosageInstruction[=].sequence = 1
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #ACM
* dosageInstruction[=].route = $SCTIE#34206005 "Subcutaneous route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 6 '[iU]' "units"
* dosageInstruction[+].text = "Inject 4 units before lunch"
* dosageInstruction[=].sequence = 1
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #ACD
* dosageInstruction[=].route = $SCTIE#34206005 "Subcutaneous route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 4 '[iU]' "units"
* dosageInstruction[+].text = "Inject 8 units before the evening meal"
* dosageInstruction[=].sequence = 1
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #ACV
* dosageInstruction[=].route = $SCTIE#34206005 "Subcutaneous route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 8 '[iU]' "units"
* dispenseRequest.quantity = 10 $SCT#732988008 "Cartridge"
* dispenseRequest.numberOfRepeatsAllowed = 3
* dispenseRequest.validityPeriod.start = "2026-10-02"
* dispenseRequest.validityPeriod.end = "2027-04-01"
* substitution.allowedBoolean = true

Instance: hiqa-grp-epg12-insulin
InstanceOf: IEMpdPrescriptionGroupHeader
Usage: #example
Title: "ePG 12 – Prescription group header: basal-bolus insulin, two medicines"
Description: "Group-level data (HIQA EP 3.1 to 3.5) for ePG 12: 2 electronic prescriptions issued together."
* status = #active
* insert PrescriptionGroup(9-RX-2026-000012, hiqa-patient-tomas-quinn, 2026-10-02T11:00:00+01:00, hiqa-rx-epg12-glargine)
* action[+].resource = Reference(hiqa-rx-epg12-aspart)

Instance: hiqa-bundle-epg12-insulin
InstanceOf: IEMpdElectronicPrescriptionGroup
Usage: #example
Title: "ePG 12 – Electronic Prescription Group: basal-bolus insulin, two medicines"
Description: "A basal-bolus insulin regimen as two electronic prescriptions issued together: insulin glargine once a day at bedtime and insulin aspart with each meal (three concurrent dosages with sequence 1). Doses in UCUM international units; supply in SNOMED CT units of presentation (Pen, Cartridge)."
* identifier.system = $NePS
* identifier.value = "9-RX-2026-000012"
* type = #collection
* timestamp = "2026-10-02T11:00:00+01:00"
* insert HIQAEntry(Patient, hiqa-patient-tomas-quinn)
* insert HIQAEntry(RequestGroup, hiqa-grp-epg12-insulin)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg12-glargine)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg12-aspart)
* insert HIQAEntry(List, hiqa-allergies-tomas-nilknown)
* insert HIQAEntry(PractitionerRole, hiqa-role-gp-nolan)
* insert HIQAEntry(Practitioner, hiqa-prac-gp-nolan)
* insert HIQAEntry(Organization, hiqa-org-gp-practice)
* insert HIQAEntry(Medication, ie-medication-insulin-glargine)
* insert HIQAEntry(Medication, ie-medication-insulin-aspart)

// ═══ ePG 13: depression and reflux, two medicines (one brand-specific) ═══

Instance: hiqa-rx-epg13-sertraline
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 13 – eP 1: sertraline 50 mg in the morning, do not substitute"
Description: "Sertraline 50 mg (NMPC VMP 268301000220104) for depression, taken in the morning (timing.repeat.when MORN); substitution not allowed, with the reason (HIQA EP 3.5.10.2, 3.5.10.3)."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000013-1"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000013"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-medication-sertraline-50)
* subject = Reference(hiqa-patient-niamh-keane)
* supportingInformation = Reference(hiqa-allergies-niamh)
* authoredOn = "2026-10-03T10:20:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#35489007 "Depressive disorder"
* dosageInstruction[0].text = "Take one tablet in the morning"
* dosageInstruction[=].patientInstruction = "Take every morning. Do not stop suddenly; talk to your GP first."
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #MORN
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732936001 "Tablet"
* dispenseRequest.quantity = 28 $SCT#732936001 "Tablet"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.numberOfRepeatsAllowed = 5
* dispenseRequest.validityPeriod.start = "2026-10-03"
* dispenseRequest.validityPeriod.end = "2027-04-03"
* substitution.allowedBoolean = false
* substitution.reason.text = "Patient stabilised on the current product; prescriber asks that it is not changed"

Instance: hiqa-rx-epg13-omeprazole
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 13 – eP 2: omeprazole 20 mg before breakfast"
Description: "Omeprazole 20 mg gastro-resistant capsules (NMPC VMP 313941000220100) for gastro-oesophageal reflux disease, before breakfast (ACM)."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000013-2"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000013"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-medication-omeprazole-20)
* subject = Reference(hiqa-patient-niamh-keane)
* supportingInformation = Reference(hiqa-allergies-niamh)
* authoredOn = "2026-10-03T10:20:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#235595009 "Gastroesophageal reflux disease"
* dosageInstruction[0].text = "Take one capsule once a day before breakfast"
* dosageInstruction[=].additionalInstruction = $SCTIE#311501008 "Half to one hour before food"
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.when = #ACM
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732937005 "Capsule"
* dispenseRequest.quantity = 28 $SCT#732937005 "Capsule"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.numberOfRepeatsAllowed = 5
* dispenseRequest.validityPeriod.start = "2026-10-03"
* dispenseRequest.validityPeriod.end = "2027-04-03"
* substitution.allowedBoolean = true

Instance: hiqa-grp-epg13-sertraline-omeprazole
InstanceOf: IEMpdPrescriptionGroupHeader
Usage: #example
Title: "ePG 13 – Prescription group header: depression and reflux, two medicines (one brand-specific)"
Description: "Group-level data (HIQA EP 3.1 to 3.5) for ePG 13: 2 electronic prescriptions issued together."
* status = #active
* insert PrescriptionGroup(9-RX-2026-000013, hiqa-patient-niamh-keane, 2026-10-03T10:20:00+01:00, hiqa-rx-epg13-sertraline)
* action[+].resource = Reference(hiqa-rx-epg13-omeprazole)

Instance: hiqa-bundle-epg13-sertraline-omeprazole
InstanceOf: IEMpdElectronicPrescriptionGroup
Usage: #example
Title: "ePG 13 – Electronic Prescription Group: depression and reflux, two medicines (one brand-specific)"
Description: "Two continuous electronic prescriptions issued together for a patient with a recorded penicillin allergy (the allergy statement lists it): sertraline in the morning with substitution not allowed (reason given, ie-rx-subst-1), and omeprazole before breakfast with 311501008 |Half to one hour before food|."
* identifier.system = $NePS
* identifier.value = "9-RX-2026-000013"
* type = #collection
* timestamp = "2026-10-03T10:20:00+01:00"
* insert HIQAEntry(Patient, hiqa-patient-niamh-keane)
* insert HIQAEntry(RequestGroup, hiqa-grp-epg13-sertraline-omeprazole)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg13-sertraline)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg13-omeprazole)
* insert HIQAEntry(List, hiqa-allergies-niamh)
* insert HIQAEntry(AllergyIntolerance, hiqa-allergy-niamh-penicillin)
* insert HIQAEntry(PractitionerRole, hiqa-role-gp-nolan)
* insert HIQAEntry(Practitioner, hiqa-prac-gp-nolan)
* insert HIQAEntry(Organization, hiqa-org-gp-practice)
* insert HIQAEntry(Medication, ie-medication-sertraline-50)
* insert HIQAEntry(Medication, ie-medication-omeprazole-20)

// ═══ ePG 14: atrial fibrillation and hypertension, loading dose then maintenance ═══

Instance: hiqa-rx-epg14-warfarin
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 14 – eP 1: warfarin 5 mg, loading then maintenance"
Description: "Warfarin 5 mg (NMPC VMP 718731000220101) for atrial fibrillation: sequence 1, two tablets once a day for 2 days; sequence 2, one tablet once a day as directed by the anticoagulation clinic."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000014-1"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000014"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-medication-warfarin-5)
* subject = Reference(hiqa-patient-declan-walsh)
* supportingInformation = Reference(hiqa-allergies-declan-nilknown)
* authoredOn = "2026-10-05T16:00:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#49436004 "Atrial fibrillation"
* dosageInstruction[0].text = "Take two tablets (10 mg) once a day for 2 days"
* dosageInstruction[=].sequence = 1
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.boundsDuration = 2 'd' "days"
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 2 $SCT#732936001 "Tablet"
* dosageInstruction[+].text = "Then take one tablet (5 mg) once a day, or as directed by the anticoagulation clinic"
* dosageInstruction[=].sequence = 2
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732936001 "Tablet"
* dispenseRequest.quantity = 28 $SCT#732936001 "Tablet"
* dispenseRequest.validityPeriod.start = "2026-10-05"
* dispenseRequest.validityPeriod.end = "2026-11-05"
* substitution.allowedBoolean = true

Instance: hiqa-rx-epg14-lisinopril
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 14 – eP 2: lisinopril 10 mg once a day"
Description: "Lisinopril 10 mg (NMPC VMP 714701000220101, ATC C09AA03) for hypertensive disorder."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000014-2"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000014"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(ie-medication-lisinopril-10)
* subject = Reference(hiqa-patient-declan-walsh)
* supportingInformation = Reference(hiqa-allergies-declan-nilknown)
* authoredOn = "2026-10-05T16:00:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#38341003 "Hypertensive disorder"
* dosageInstruction[0].text = "Take one tablet once a day"
* dosageInstruction[=].timing.repeat.frequency = 1
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 1 $SCT#732936001 "Tablet"
* dispenseRequest.quantity = 28 $SCT#732936001 "Tablet"
* dispenseRequest.expectedSupplyDuration = 28 'd' "days"
* dispenseRequest.validityPeriod.start = "2026-10-05"
* dispenseRequest.validityPeriod.end = "2026-11-05"
* substitution.allowedBoolean = true

Instance: hiqa-grp-epg14-warfarin-lisinopril
InstanceOf: IEMpdPrescriptionGroupHeader
Usage: #example
Title: "ePG 14 – Prescription group header: atrial fibrillation and hypertension, loading dose then maintenance"
Description: "Group-level data (HIQA EP 3.1 to 3.5) for ePG 14: 2 electronic prescriptions issued together."
* status = #active
* insert PrescriptionGroup(9-RX-2026-000014, hiqa-patient-declan-walsh, 2026-10-05T16:00:00+01:00, hiqa-rx-epg14-warfarin)
* action[+].resource = Reference(hiqa-rx-epg14-lisinopril)

Instance: hiqa-bundle-epg14-warfarin-lisinopril
InstanceOf: IEMpdElectronicPrescriptionGroup
Usage: #example
Title: "ePG 14 – Electronic Prescription Group: atrial fibrillation and hypertension, loading dose then maintenance"
Description: "Two electronic prescriptions issued together: warfarin with two consecutive dosage schemes (sequence 1 loading for 2 days, sequence 2 maintenance) and lisinopril once a day."
* identifier.system = $NePS
* identifier.value = "9-RX-2026-000014"
* type = #collection
* timestamp = "2026-10-05T16:00:00+01:00"
* insert HIQAEntry(Patient, hiqa-patient-declan-walsh)
* insert HIQAEntry(RequestGroup, hiqa-grp-epg14-warfarin-lisinopril)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg14-warfarin)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg14-lisinopril)
* insert HIQAEntry(List, hiqa-allergies-declan-nilknown)
* insert HIQAEntry(PractitionerRole, hiqa-role-gp-nolan)
* insert HIQAEntry(Practitioner, hiqa-prac-gp-nolan)
* insert HIQAEntry(Organization, hiqa-org-gp-practice)
* insert HIQAEntry(Medication, ie-medication-warfarin-5)
* insert HIQAEntry(Medication, ie-medication-lisinopril-10)

// ═══ ePG 15: child under 12, antibiotic and reliever inhaler ═══

Instance: hiqa-rx-epg15-amoxicillin
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 15 – eP 1: amoxicillin 250 mg/5 mL, 5 mL three times a day for 5 days"
Description: "Amoxicillin 250 mg/5 mL oral suspension (NMPC VMP 462991000220107) for acute otitis media: liquid dose in UCUM mL, time bounds of 5 days, 421984009 |Until finished|."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000015-1"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000015"
* extension[ageAtPrescribing].valueAge = 5 'a' "years"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#acute "Short course (acute) therapy"
* medicationReference = Reference(hiqa-med-amoxicillin-50mgml-susp)
* subject = Reference(hiqa-patient-oisin-brady)
* supportingInformation = Reference(hiqa-allergies-oisin-nilknown)
* authoredOn = "2026-10-06T09:40:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#3110003 "Acute otitis media"
* dosageInstruction[0].text = "Give 5 mL (250 mg) three times a day for 5 days. Finish the course"
* dosageInstruction[=].patientInstruction = "Shake the bottle well. Use the oral syringe provided."
* dosageInstruction[=].additionalInstruction = $SCTIE#421984009 "Until finished"
* dosageInstruction[=].timing.repeat.frequency = 3
* dosageInstruction[=].timing.repeat.period = 1
* dosageInstruction[=].timing.repeat.periodUnit = #d
* dosageInstruction[=].timing.repeat.boundsDuration = 5 'd' "days"
* dosageInstruction[=].route = $SCTIE#26643006 "Oral route"
* dosageInstruction[=].doseAndRate[0].doseQuantity = 5 'mL' "mL"
* dispenseRequest.quantity = 100 'mL' "mL"
* dispenseRequest.validityPeriod.start = "2026-10-06"
* dispenseRequest.validityPeriod.end = "2026-11-06"
* substitution.allowedBoolean = true

Instance: hiqa-rx-epg15-salbutamol
InstanceOf: IEMpdMedicationRequestEPrescription
Usage: #example
Title: "ePG 15 – eP 2: salbutamol inhaler, 1 to 2 puffs when needed"
Description: "Salbutamol 100 micrograms/actuation inhaler (NMPC VMP 363291000220101) for asthma: as needed (asNeededBoolean, HL7 Europe MPD), dose range 1 to 2 actuations, at most 8 in 24 hours; supply of 200 actuations."
* identifier[0].system = $NePS
* identifier[=].value = "9-RX-2026-000015-2"
* groupIdentifier.system = $NePS
* groupIdentifier.value = "9-RX-2026-000015"
* extension[ageAtPrescribing].valueAge = 5 'a' "years"
* status = #active
* intent = #order
* courseOfTherapyType = http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy#continuous "Continuous long term therapy"
* medicationReference = Reference(hiqa-med-salbutamol-inhaler)
* subject = Reference(hiqa-patient-oisin-brady)
* supportingInformation = Reference(hiqa-allergies-oisin-nilknown)
* authoredOn = "2026-10-06T09:40:00+01:00"
* requester = Reference(hiqa-role-gp-nolan)
* reasonCode = $SCTIE#195967001 "Asthma"
* dosageInstruction[0].text = "Inhale 1 to 2 puffs through the spacer when needed for wheeze. Maximum 8 puffs in 24 hours"
* dosageInstruction[=].asNeededBoolean = true
* dosageInstruction[=].route = $SCTIE#447694001 "Respiratory tract route"
* dosageInstruction[=].doseAndRate[0].doseRange.low = 1 $SCT#732981002 "Actuation"
* dosageInstruction[=].doseAndRate[0].doseRange.high = 2 $SCT#732981002 "Actuation"
* dosageInstruction[=].maxDosePerPeriod.numerator = 8 $SCT#732981002 "Actuation"
* dosageInstruction[=].maxDosePerPeriod.denominator = 24 'h' "hours"
* dispenseRequest.quantity = 200 $SCT#732981002 "Actuation"
* dispenseRequest.validityPeriod.start = "2026-10-06"
* dispenseRequest.validityPeriod.end = "2026-11-06"
* substitution.allowedBoolean = true

Instance: hiqa-grp-epg15-paediatric
InstanceOf: IEMpdPrescriptionGroupHeader
Usage: #example
Title: "ePG 15 – Prescription group header: child under 12, antibiotic and reliever inhaler"
Description: "Group-level data (HIQA EP 3.1 to 3.5) for ePG 15: 2 electronic prescriptions issued together."
* status = #active
* insert PrescriptionGroup(9-RX-2026-000015, hiqa-patient-oisin-brady, 2026-10-06T09:40:00+01:00, hiqa-rx-epg15-amoxicillin)
* action[+].resource = Reference(hiqa-rx-epg15-salbutamol)

Instance: hiqa-bundle-epg15-paediatric
InstanceOf: IEMpdElectronicPrescriptionGroup
Usage: #example
Title: "ePG 15 – Electronic Prescription Group: child under 12, antibiotic and reliever inhaler"
Description: "Two electronic prescriptions issued together for a 5-year-old (age at prescribing recorded on each eP, HIQA EP 1.4.2): amoxicillin suspension dosed in mL for 5 days, and a salbutamol inhaler as needed with a dose range and a maximum dose."
* identifier.system = $NePS
* identifier.value = "9-RX-2026-000015"
* type = #collection
* timestamp = "2026-10-06T09:40:00+01:00"
* insert HIQAEntry(Patient, hiqa-patient-oisin-brady)
* insert HIQAEntry(RequestGroup, hiqa-grp-epg15-paediatric)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg15-amoxicillin)
* insert HIQAEntry(MedicationRequest, hiqa-rx-epg15-salbutamol)
* insert HIQAEntry(List, hiqa-allergies-oisin-nilknown)
* insert HIQAEntry(PractitionerRole, hiqa-role-gp-nolan)
* insert HIQAEntry(Practitioner, hiqa-prac-gp-nolan)
* insert HIQAEntry(Organization, hiqa-org-gp-practice)
* insert HIQAEntry(Medication, hiqa-med-amoxicillin-50mgml-susp)
* insert HIQAEntry(Medication, hiqa-med-salbutamol-inhaler)
